#!/bin/sh

# update-test-files
#
# A number of tests depend on test files being generated by the current
# version of the tool using the current schema version.
#
# This script:
# - Updates the AllProposals snapshot to include all proposals on the main branch of the swift-evolution repo
# - Regenerates all other snapshots used for testing from the existing snapshot
# - Additional handling of SameCommit and WithUpdates snapshots to update prevoius results to latest tool/schema versions
# - Regenerates metadata json files used for testing proper version handling behavior
#
# The script can also be called with a single argument - the name of a single snapshot to update.
# This functionality is used in the 'update-all-proposals-snapshot.sh' script.
#
#
# The old snapshots/files are moved to a 'ReplacedFiles' directory.
#
# The intended workflow is to inspect the changes of the newly generated snapshots/files,
# ensure tests pass, commit the changes, and delete the ReplacedFiles directory and its contents.
#


single_snapshot=$1

if [[ $single_snapshot == "" ]]; then
    echo "\nUpdating test files. Original files will be placed in the 'ReplacedFiles' directory.\n"
else
    echo "\nUpdating '$single_snapshot' snapshot. Original snapshot will be placed in the 'ReplacedFiles' directory.\n"
fi

script_dir=$(dirname "$(readlink -f "$0")")
package_dir=$(readlink -f $script_dir/..)
seme_command="$package_dir/.build/release/swift-evolution-metadata-extractor"
test_resources_dir="$package_dir/Tests/ExtractionTests/Resources"
expected_results_file="expected-results.json"
previous_results_file="previous-results.json"

# Create directory for replaced files
replaced_files_dir="$test_resources_dir/ReplacedFiles"
mkdir $replaced_files_dir

if [ $? -ne 0 ]; then
    echo "\nDirectory 'ReplacedFiles' still exists. Ensure that replaced files are no longer needed, delete the 'ReplacedFiles' directory and re-run the script.\n"
    exit
else
    echo "Creating directory 'ReplacedFiles'."
fi

# Change to package directory. Clean and build swift-evolution-metadata-extractor tool.
cd $package_dir

echo "\nClean swift-evolution-metadata-extractor package\n"
swift package clean

echo "Build swift-evolution-metadata-extractor\n"
swift build -c release

# For each snapshot in the test resources directory
for file in ${test_resources_dir}/*.evosnapshot
do
    snapshot_name=$(basename $file .evosnapshot)

    # Filter on command line argument
    if [[ $single_snapshot == "" ]] || [[ $single_snapshot == $snapshot_name ]] || [[ "${single_snapshot}-BaseCommit" == $snapshot_name ]]; then

        snapshot_path="$test_resources_dir/$snapshot_name.evosnapshot"
        new_snapshot_path="$test_resources_dir/$snapshot_name-NEW.evosnapshot"

        # When updating AllProposals always fetch latest from repository
        if [[ $snapshot_name == "AllProposals" ]]; then
            $seme_command snapshot -o $new_snapshot_path
            readme_path="$snapshot_path/README.txt"
            cp $readme_path "$new_snapshot_path/README.txt"
        else
            $seme_command snapshot --snapshot-path $snapshot_path -o $new_snapshot_path
        fi


        # The SameCommit snapshot tests reuse of the previous results
        # if the commit is the same and the versions haven't changed.
        # In the test bundle, this means the previous results is the same as the expected results
        if [ $snapshot_name == "SameCommit" ]; then
                        
            previous_creation_date=$(grep "creationDate" "$snapshot_path/$previous_results_file")

            # The existing, outdated previous-results.json file will be copied to new snapshot.
            # Copy the newly generated expected-results.json to previous-results.json
            # and use the creation date field of the prior previous-results.json file

            cp "$new_snapshot_path/$expected_results_file" "$new_snapshot_path/$previous_results_file"
            sed -i '' "s/ *\"creationDate\" : \".*\",/$previous_creation_date/" "$new_snapshot_path/$previous_results_file"
        fi
        
        mv $snapshot_path $replaced_files_dir
        mv $new_snapshot_path $snapshot_path

    fi
#   echo "$file"
done

# Move expected results of base commit snapshot to be the previous results of WithUpdates snapshot
if [[ $single_snapshot == "" ]] || [[ $single_snapshot == "WithUpdates" ]]; then

    prior_snapshot_path="$test_resources_dir/WithUpdates-BaseCommit.evosnapshot"
    new_snapshot_path="$test_resources_dir/WithUpdates.evosnapshot"
    
    echo "Prior: $prior_snapshot_path/$expected_results_file"
    echo "Updated: $new_snapshot_path/$previous_results_file"
    
    # The existing, outdated previous-results.json file will be copied to new snapshot.
    # Copy the newly generated expected-results.json to previous-results.json
    # and use the creation date field of the prior previous-results.json file

    cp "$prior_snapshot_path/$expected_results_file" "$new_snapshot_path/$previous_results_file"
fi


# Update metadata version test files
#
# These files are used in tests that rely on the values of the toolVersion and schemaVersion fields
# They contain the metadata of two proposals and use the values "0.1.0" and "0.9.0" to represent
# old versions for toolVersion and schemaVersion respectively.
# Except for these fields, the files are identical.

# Only update if all test files are being updated
if [[ $single_snapshot == "" ]]; then

    proposal_files_dir="$test_resources_dir/ProposalFiles"
    metadata_version_files_dir="$test_resources_dir/MetadataVersions"
    replaced_metadata_version_files_dir="$replaced_files_dir/MetadataVersions"
    mkdir $replaced_metadata_version_files_dir

    current_metadata_versions_file="$metadata_version_files_dir/current-metadata-versions.json"
    replaced_current_metadata_versions_file="$replaced_metadata_version_files_dir/current-metadata-versions.json"
    
    previous_creation_date=$(grep "creationDate" $current_metadata_versions_file)

    mv $current_metadata_versions_file $replaced_current_metadata_versions_file
    $seme_command -o $current_metadata_versions_file "$proposal_files_dir/0300-continuation.md" "$proposal_files_dir/0422-caller-side-default-argument-macro-expression.md"
    sed -i '' "s/ *\"creationDate\" : \".*\",/$previous_creation_date/" $current_metadata_versions_file
    
    
    old_tool_version_file="$metadata_version_files_dir/old-tool-version.json"
    replaced_old_tool_version_file="$replaced_metadata_version_files_dir/old-tool-version.json"

    mv $old_tool_version_file $replaced_old_tool_version_file
    cp $current_metadata_versions_file $old_tool_version_file
    sed -i '' 's/"toolVersion" : "[0-9]\.[0-9]\.[0-9]"/"toolVersion" : "0\.0\.9"/' $old_tool_version_file


    old_schema_version_file="$metadata_version_files_dir/old-schema-version.json"
    replaced_old_schema_version_file="$replaced_metadata_version_files_dir/old-schema-version.json"

    mv $old_schema_version_file $replaced_old_schema_version_file
    cp $current_metadata_versions_file $old_schema_version_file
    sed -i '' 's/"schemaVersion" : "[0-9]\.[0-9]\.[0-9]"/"schemaVersion" : "0\.9\.0"/' $old_schema_version_file

fi


